### PR TITLE
Extract ExternalServices and TumblerClientConfiguration parent types

### PR DESCRIPTION
**Pull request by bokobza**
I created parent classes for ExternalServices and TumblerClientConfiguration so that a custom config can be used with the TumblerClientRuntime, without having any dependency on RPC or any configuration file.
This will be particularly useful for the Breeze Client as it doesn't have access to a Bitcoin Core node and won't be using a configuration file to initialize the runtime.
Tests are passing :-)

### CODE REVIEW

**Comment by NicolasDorier** [comment]
Ok so basically you moved some initialization logic from TumblerClientRuntime to TumblerClientConfiguration.

This should not be done. TumblerClientRuntime is the class responsible for checking the configuration is correctly aside of parsing (can connect to RPC etc...)

Same thing, the initialization of the repository should be done in TumblerClientRuntime.

**Comment by NicolasDorier** [comment]
I would expect the user do something like

```
TumblerClientRuntime runtime = new ...();
runtime.ExternalServices = myServices;
runtime.Repository = repository;
runtime.Configure(tumblerClientConfig);
```

Configure would skip the parts which would normally create the ExternalServices and Repository for you, since it is already set.

**Comment by bokobza** [comment]
This initialization logic has no dependencies on the TumblerClientRuntime: all these objects depends on other config settings only and there's nothing the TumblerClientRuntime adds to the logic.  


> Same thing, the initialization of the repository should be done in TumblerClientRuntime.

Most of the other config objects are initialized in the TumblerClientConfiguration and assigned to a corresponding object in the TumblerClientRuntime. Why does the repository have to be initialized in the TumblerClientRuntime? 

> I would expect the user do something like

>TumblerClientRuntime runtime = new ...();
runtime.ExternalServices = myServices;
runtime.Repository = repository;
runtime.Configure(tumblerClientConfig);
Configure would skip the parts which would normally create the ExternalServices and Repository for you, since it is already set.

That's not going to work if you don't want to use RPC. First of all, the ConfigureAsync method would fail due to the lack of configuration defined for RPC. Then, even if the RPC config details were set, the ExternalServices would get overriden during the ConfigureAsync call. 
Furthermore, relying on code skipping parts during initialization would require intimate knowledge of the inside of methods. It would be safer to rely on the programming interface these methods are offering.

What I wanted to avoid is having to rely on RPC and config files for the client, while still reusing the same TumblerClientRuntime and TumblerClientConfiguration classes.

**Comment by NicolasDorier** [comment]
> What I wanted to avoid is having to rely on RPC and config files for the client, while still reusing the same TumblerClientRuntime and TumblerClientConfiguration classes.

Yes I understand that.

> Then, even if the RPC config details were set, the ExternalServices would get overriden during the ConfigureAsync call.

No, this is my point.

You create the runtime like this:

```
TumblerClientRuntime runtime = new ...();
runtime.ExternalServices = myServices;
runtime.Repository = repository;
await runtime.ConfigureAsync(tumblerClientConfig);
```

In ConfigureAsync you then do

```
if(this.ExternalServices == null)
{
 //use current RPC intialization
}
```

By doing so, old code will just behave the same, while letting you override things.
What do you think ?

**Comment by bokobza** [comment]
Ah yes @NicolasDorier I can do it like this for sure, but then I have a few questions:
do I check pre-existence for every property of TumblerClientRuntime? 
if not, how do I let the user know that only ExternalServices won't be overridden? By having it in the constructor maybe?
I think it's cleaner if you encourage the consumers of your library to provide their own implemented object for configuration (or use the default one). This way, no need for too many ifs.

I'll try the way you suggested, see if I can do something nice :-)
Thanks

**Comment by NicolasDorier** [comment]
I just want to avoid any external access in the configuration class.
Do check the existence of properties only for what matter to Breeze.

If it becomes a pain in the ass later, we'll refactor. I just prefer be sure not too much code is changed by now.

**Comment by bokobza** [comment]
Sure, no problem. thanks for looking at it :-)

**Pull request closed without merging**
