### PR TITLE
Tor integration

### PR DESCRIPTION
**Pull request by nopara73**
I finished the Tor integration and tested it on Ubuntu and Windows 7. It works flawlessly.  
  
# Setting up Tor  
  
There is no need for the user to do any settings manually, except that the user has to make sure Tor is in the PATH of its operating system.  
  
# Local vs remote
If the Tumbler is running locally, it will not use Tor. Therefore a remote server is needed for testing. For this purpose I used @NicolasDorier 's testnet tumbler server, which can be set up in the client.config file as follows: `tumbler.server=http://testnet.ntumblebit.metaco.com`.  

# What it does?  
  
Whenever any HTTP request is sent to the Tumbler the it checks if the identity the software wants to send the request is the same as the last request was sent with and if it's not it chanes Tor circuit, before the request is sent.  
  
An identity is defined by TumbleBit's Alice Bob role's and the cycle they are in.  

## Example:  
```
CHANGE IP: 0 sec
	Alice 1152052
	POST /api/v1/tumblers/0/clientchannels/confirm


CHANGE IP: 4 sec
	Alice 1152054
	POST /api/v1/tumblers/0/clientchannels/


CHANGE IP: 0 sec
	Bob 1152052
	POST /api/v1/tumblers/0/channels/
	Bob 1152052
	POST /api/v1/tumblers/0/channels/1152052/a914ae1cb6ddde39f7b9fe4d8027fbe06809d8d057cd87/signhashes
	Bob 1152052
	POST /api/v1/tumblers/0/channels/1152052/a914ae1cb6ddde39f7b9fe4d8027fbe06809d8d057cd87/checkrevelation


CHANGE IP: 0 sec
	Bob 1152058
	GET /api/v1/tumblers/0/vouchers/
```
  
# Additional notes / ToDo  
  
- [ ] Before merge -  I am writing a torchangelog.txt inside the NTumbleBit.ClassicTumbler.Client.CLI directory. This is a quick messy logging it must be removed. The output of this file is the example above.
- [ ] After merge - Update the wiki
  
# Big picture 
This is the last major milestone that'll make TumbleBit protocol implementation a complete Bitcoin anonymity technique. The rest is UX, bug fixing and optimization.

### CODE REVIEW

**Comment by NicolasDorier** [comment]
No need to remove the HTTP proxy support.
Also no need to change the `TumblerClient` methods. Just having a `Runtime.CreateClient(int cycle, bool isAlice)` instead of the properties Alice/Bob.

I can fix on top of your PR or you do?

**Comment by nopara73** [comment]
> No need to remove the HTTP proxy support.  
  
In that case a simple TumbleBit Sudoku by the Tumbler will deanonymize the users:
    
TumbleBit Sudoku

> Also no need to change the TumblerClient methods. Just having a Runtime.CreateClient(int cycle, bool isAlice) instead of the properties Alice/Bob. I can fix on top of your PR or you do?  
  
Yes do it please, I'm not entirely sure what you mean.

**Comment by NicolasDorier** [comment]
I would say that the same HTTP Proxy can be shared by multiple Alice. Or some people might still want to use privoxy because it is already set up in their environment.

@EthanHeilman what do you think? Should we drop the ability to configure an http proxy on TB? Anyway, I think it is better we remove proxy support on a separate commit.

**Comment by nopara73** [comment]
There is a memory leak. I don't know if it's because of my Tor integration or not, if you run the software for half a day or more you'll see it eating up the memory.  
I am testing it now without Tor integration. I'll come back with the results.

**Comment by nopara73** [comment]
@NicolasDorier Please revert these commits and work on this branch.
https://github.com/NTumbleBit/NTumbleBit/commit/d1cb4cbcda3b248c85b1b23fe27e917c81cfe87f
https://github.com/NTumbleBit/NTumbleBit/commit/ad664124ab61c75ba623965f5322471c27c14f65
https://github.com/NTumbleBit/NTumbleBit/commit/e08c2a32e99bee3dba12d26d09dfe31a4c5cd21a

You created many conflicts, also an "Identity" class that has different meanining in my implementation.

**Comment by EthanHeilman** [comment]
@NicolasDorier @nopara73 The tumbler should commit to a single way of communicating with the users when it commits to the pubkey and other public parameters to prevent fingerprint by IP address or privacy method used.
1. We should use TOR by default, but have an option to disable it for testing without TOR.
2. The code should call a Communication superclass rather than the TOR class direct to enable adding new communication methods in case TOR becomes obsolete or Bitcoin network privacy services are developed and deployed.

**Pull request closed without merging**
