### PR TITLE
Implement patient recursive directory delete

### PR DESCRIPTION
**Pull request by nopara73**
https://github.com/NTumbleBit/NTumbleBit/issues/13

### CODE REVIEW

**Comment by NicolasDorier** [comment]
Can you throw the last exception if 10 gnomes are past

**Comment by nopara73** [comment]
The code doesn't catch them

**Comment by NicolasDorier** [comment]
so save it in variable and throw. We do not want silent failure.

**Comment by NicolasDorier** [comment]
this does not rethrow the last exception.

**Comment by nopara73** [comment]
There is no silent exception, neither in my first, nor in my second code:  
```cs
private static void ThrowException()
{
	try
	{
		File.ReadAllLines("IDontExists.txt");
	}
	catch (ArgumentNullException)
	{

	}
}
```

```cs
private static void ThrowException()
{
	try
	{
		File.ReadAllLines("IDontExists.txt");
	}
	catch (ArgumentNullException)
	{

	}
	catch(Exception)
	{
		throw;
	}
}
```

**Comment by NicolasDorier** [comment]
if IOException is raised ten times, the function happily exit without error.

**Comment by nopara73** [comment]
You are right, my bad. I fixed it and tested if it still solves problems or just silence the exception.  
It still solves problems, the magic gnomes doesn't max out.

**Comment by nopara73** [comment]
[Yes!](https://www.youtube.com/watch?v=7kF4bGqafNI)

**Pull request merged**
