### PR TITLE
WIP: Tor integration (testing needed)

### PR DESCRIPTION
**Pull request by nopara73**
Tor integration. Do not merge, testing needed.  
  
You cannot test it on your local machine, since a Tor exit node cannot access your localhost.  
I set up a tumbler server, use that instead:  

`tumbler.server=http://146.185.160.175:5000`

Lines added to the `client.config` file:  
```
tor.use=true
tor.host=127.0.0.1
tor.socksport=9050
tor.controlport=9051
tor.controlportpassword=ILoveBitcoin21
```

# Tor instructions  
1. Download Tor Expert Bundle: https://www.torproject.org/download/download
2. Download the torrc config file sample: https://github.com/nopara73/DotNetTor/blob/master/torrc
3. Place torrc in the proper default location (depending on your OS) and edit it:
  - Optionally uncomment and edit the SocksPort, if you don't uncomment it will default to 9050 port anyway
  - The default ControlPort in the sample is 9051, optionally edit it.
  - Modify the password hash
    - To run my tests, for the `ControlPortPassword = "ILoveBitcoin21"` the hash should be: `HashedControlPassword 16:0978DBAF70EEB5C46063F3F6FD8CBC7A86DF70D2206916C1E2AE29EAF6`
    - For your application you should use different one, a more complicated one. Then start tor like this: `tor --hash-password password`
      where password is the `password` you've chosen. It will give you the `HashedControlPassword`.
4. Start tor, it will listen to the ports you set in the config file.

### CODE REVIEW

**Comment by nopara73** [comment]
Here's an error I sometimes encounter only with Tor. Probably after I stop the client with ctrl+c.
```
info: Configuration[0]
      Downloading tumbler information of http://146.185.160.175:5000/
fail: Configuration[0]
      Unterminated string. Expected delimiter: ". Path 'voucherKey', line 1, position 1024.
dbug: Configuration[0]
         at NTumbleBit.CLI.Program.Retry[T](Int32 count, Func`1 act) in /home/user/NTumbleBit/NTumbleBit.CLI/Program.cs:line 211
         at NTumbleBit.CLI.Program.Main(String[] args) in /home/user/NTumbleBit/NTumbleBit.CLI/Program.cs:line 111
```

**Comment by NicolasDorier** [comment]
can you rebase ?

**Comment by nopara73** [comment]
I'd wait until NTumbleBit upgrades to the new .NET Core. I don't want to spend half a day to figure out how to have both on my system.

**Comment by NicolasDorier** [comment]
can you rebase now I updated the project ?

**Comment by unsystemizer** [comment]
> a Tor exit node cannot access your localhost

If you allow it (in torrc) it can, though. But I'll test it as per the instructions.

**Pull request closed without merging**
