### PR TITLE
Remove Socks and HTTP proxy

### PR DESCRIPTION
**Pull request by nopara73**
# Motivation
Malicious code has been commited to the master branch without any review and discussion under the name of configurability. The code does not have any testing purpose.  
At best it misleads those users who are using the tumbler with proper configuration about their anonymity set and deanonimizes those who is using it with the removed configuration.  
At worst if most user is using it with the removed configuration, they will be deanonymized, as the following illustration explains:  
TumbleBit Sudoku  
  
# Removed
- Socks proxy
- HTTP proxy

# Rationale
## Socks proxy  
  
This way of using TumbleBit, a simple TumbleBit sudoku by the Tumbler results in complete deanonymization of every user, since the Client only creates one Alice and one Bob identity, not tied to cycles.  
  
Furthermore mixed usage of this mode and other modes will also tell the Tumbler who's using this mode based on the HTTP headers or other network information. Even one whitespace or the lack of it is a track.
  
## HTTP Proxy  
  
Everything applies to HTTP proxy that applies to Socks proxy, plus that it can be more easily recognized by the tumbler, because it is using clear IP.  
Using a clearnet proxy also doesn't attempt to hide the identity of the user agent, therefore it results further attack surfaces.

### CODE REVIEW

**Comment by NicolasDorier** [comment]
ping @EthanHeilman is it unreasonable to allow an advanced user to configure custom proxy http / proxy SOCKS, when it is using full Tor?

By selecting cycle carefully, we can make sure there is never 2 cycles overlapping an update on 3 blocks (which would naturally provoke the creation of new circuit).

It allows advanced user to use some other services for privacy like https://privatoria.net/ , or to have its own infrastructure, which might already host 2 router gateway routing traffic through tor/vpn.

@nopara73 graphs have 2 flaws, one is to assume Alice5 in two cycles can be linked. Since it is advanced user settings, I don't think they would do such error. (If either Alice or Bob change IP, then this does not hold)
And even if they configure wrong, Alice5 does not hurt privacy of other, as the alternative: Alice5 not using TumbleBit because of lack of advanced features/settings, would be worse for everyone.

**Comment by nopara73** [comment]
> is it unreasonable to allow an advanced user to configure custom proxy http / proxy SOCKS, when it is using full Tor?  
  
If everyone else is using different Alice and Bob per cycle and you are using the same, even in 2 cycles you are already deanonymized by the Tumbler. But you probably won't have to wait that long, since other network parameters will tell you are different from the rest of the users. For example many HTTP clients are sending the headers and statline in different ways. Some include full path into the request line, some doesn't. Or the headers can be sent in various ways, like: `Host: tumblebit.com`, `Host : tumblebit.com`, `Host :tumblebit.com` or `Host:tumblebit.com`.  
  
> By selecting cycle carefully, we can make sure there is never 2 cycles overlapping an update on 3 blocks (which would naturally provoke the creation of new circuit).  
  
My above comment applies, but also what do you expect? If a TumbleBit cycle takes half a day/one day and today's United Bitcoiner's mainnet server is mixing 0.07btc per cycle, mixing 10 bitcoin will take half a year?  
  
> It allows advanced user to use some other services for privacy like https://privatoria.net/ 
  
privotria is using: VPN + TOR + PROXY + TOR, or to have its own infrastructure, which might already host 2 router gateway routing traffic through tor/vpn. 
  
It doesn't prevent the users to use TumbleBit with correct configuration. Even if it would my previous comment would still apply. It deanonymizes them so TumbleBit loses its usefulness.  
  
> @nopara73 graphs have 2 flaws, one is to assume Alice5 in two cycles can be linked.  
  
It can, because it us using the same IP.  
  
>  Since it is advanced user settings, I don't think they would do such error. 
  
Let's suppose the client only participate in one cycle, which it won't no matter how advanced the user think he is. Then my previous comment still applies, using multiple proxies, even if both are behind Tor can be distinguished by each other based on network tracks.  
  
> (If either Alice or Bob change IP, then this does not hold)    
  
There is no such a thing implemented, but even if there would it would still hold. Beside network tracks you can come to conclusions when from Alice using the same bitcoin outputs before the mix or Bob joins mixed outputs together.  
  
> And even if they configure wrong, Alice5 does not hurt privacy of other, as the alternative: Alice5 not using TumbleBit because of lack of advanced features/settings, would be worse for everyone.  
   
The main thing to realize is: if some people uses TumbleBit improperly they hurt the anonymity set of the rest of the users. It misleads them, giving them a false illusion of privacy.

**Comment by EthanHeilman** [comment]
@NicolasDorier @nopara73 Can we setup a hangouts tomorrow and discuss this in detail figure out what we want to do?

**Comment by nopara73** [comment]
@EthanHeilman Yes, I am here all day.

**Comment by NicolasDorier** [comment]
> Or the headers can be sent in various ways, like: Host: tumblebit.com, Host : tumblebit.com, Host :tumblebit.com or Host:tumblebit.com.

What you are talking about is HTTP FingerPrinting. TCP level fingerprinting reveal the OS, and outsourcing Alice or Bob channel to another device would prevent TCP level fingerprinting.

> My above comment applies, but also what do you expect? If a TumbleBit cycle takes half a day/one day and today's United Bitcoiner's mainnet server is mixing 0.07btc per cycle, mixing 10 bitcoin will take half a year?

They can just use more BTC per cycle.

> The main thing to realize is: if some people uses TumbleBit improperly they hurt the anonymity set of the rest of the users. It misleads them, giving them a false illusion of privacy.

Some people would not use TumbleBit at all without those advanced features. Which is even worse for privacy than those same people using TumbleBit uncorrectly.
If what you said were true, then an attacker can already do the same thing.

**Pull request closed without merging**
