### PR TITLE
Adds the -help option and the server configuration documentation

### PR DESCRIPTION
**Pull request by drov0**

### CODE REVIEW

**Comment by NicolasDorier** [comment]
Here nobody will ever read it.
What you can do is to redirect the user to the page Server-configuration.md when he does `-help`, like git does. You can do that with Process.Start("link to the .md")

**Comment by nopara73** [comment]
How about me adding your config to the wiki and then you can redirect it there?  
  
I think we should not write in stone the user space just yet and only maintain the wiki, with that keeping the possibility of breaking the user space in these early stages.  
  
If that's fine for you the link will be https://github.com/NTumbleBit/NTumbleBit/wiki/Server-Config

**Comment by drov0** [comment]
OK Will do

**Comment by nopara73** [comment]
Added the page.  
I wanted to also say that you should set the your modified default port accordingly in the default config creation, then I noticed it has been commented out.  
@NicolasDorier Why has the `CreateDefaultConfiguration` and `CreateClientDefaultConfiguration` been commented out in https://github.com/NTumbleBit/NTumbleBit/blob/master/NTumbleBit.Common/TextFileConfiguration.cs ?

**Pull request merged**
