### PR TITLE
WIP: Interactive CLI

### PR DESCRIPTION
**Pull request by subhankarg**
Hi, I have made some changes to the CLI.

1.  The CLI is made interactive
2. Uses this [library](https://github.com/gsscoder/commandline)
3. `tumble` and `status` initially implemented
4. Help is available at all stages eg. `help tumble`
5. More changes to be made based on feedback

Installation:
`dotnet restore` to add the new library dependency

Typical Usage:
1. Start the interactive CLI mode by using `dotnet run -i`
2. Optionally append `-testnet` above to run on testnet
3. Type _help_ to get the list of commands available
4. To start tumbler, type _tumble_
5. Press enter to stop
6. Type _status_ to start tumbler again
7. Press enter to stop
8. Type _quit_ to exit

### CODE REVIEW

**Comment by NicolasDorier** [comment]
this is awesome. Can you fix white spaces to \r\n on `Program.cs` so I can better review ?

**Comment by NicolasDorier** [comment]
Also can you keep supporting old style ? like `-testnet` ?

**Comment by NicolasDorier** [comment]
Also it seems that it will be interactive by default. Can you make it so it is interactive if `-i` is specified ?

**Comment by subhankarg** [comment]
Thanks, I have made the above changes:
- `-testnet` and `onlymonitor` should work as before
- `-i` will invoke the interactive mode
- unix line endings `\n` restored as used in the source originally

**Comment by NicolasDorier** [comment]
I think it is /r/n look the diff

**Comment by subhankarg** [comment]
This is about the line endings in the source `Program.cs` right? The one from the master is showing only `\n` in my end.

**Comment by NicolasDorier** [comment]
ha maybe it is indeed fine, sorry. Thanks a lot I will test it.

**Comment by NicolasDorier** [comment]
@subhankarg sorry to have been a bit slow on it. This is an awesome feature, I want to get it in NTumbleBit.
My main complain about the state right now is the size of the diff. Can you arrange the code such that we do not have this big diff when most of the code is the same ?

Do not hesitate to create separate files for the option classes.

I would like that the non interactive mode use the old style parsing to be sure nothing that was working before break now. Maybe it is already the case, but reviewing is kind of hard because of the big diff.

**Comment by subhankarg** [comment]
I fixed the big diff issue and separated the options class. Mixing tabs and spaces caused the issue. Sorry about that. Please have a look now.

**Comment by NicolasDorier** [comment]
@subhankarg you should try to pull the new version. Now the CLI has a command called `status` which allow you to query cycle/transaction or address and see what is going on in the tumbler. This is awesome.

**Pull request merged**
